'use client';

import React, { useState } from 'react';
import { Check, Download, ExternalLink, Link as LinkIcon, QrCode, Share2 } from 'lucide-react';
import { Dialog, DialogContent } from '@/components/ui/dialog';

interface ShareQrDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  /** What is being shared, e.g. the contestant's name */
  name: string;
  /** Absolute or root-relative link to the public page */
  url: string;
  /** Base64 QR data URL generated by the backend */
  qrCodeData?: string | null;
  /** Optional line under the title, e.g. "Candidate #4" */
  subtitle?: string;
}

const ShareQrDialog: React.FC<ShareQrDialogProps> = ({
  open,
  onOpenChange,
  name,
  url,
  qrCodeData,
  subtitle,
}) => {
  const [copied, setCopied] = useState(false);

  const absoluteUrl =
    typeof window !== 'undefined' && url.startsWith('/') ? `${window.location.origin}${url}` : url;

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(absoluteUrl);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // Clipboard can be blocked; the link stays visible below for manual copying
    }
  };

  const handleShare = async () => {
    if (!navigator.share) return handleCopy();
    try {
      await navigator.share({ title: name, text: `Vote for ${name}`, url: absoluteUrl });
    } catch {
      // Share sheet dismissed — nothing to do
    }
  };

  const handleDownload = () => {
    if (!qrCodeData) return;
    const link = document.createElement('a');
    link.href = qrCodeData;
    link.download = `${name.replace(/\s+/g, '-').toLowerCase()}-qr.png`;
    link.click();
  };

  const actionClass =
    'flex-1 min-w-0 inline-flex items-center justify-center gap-2 px-3 py-2.5 rounded-xl border text-sm font-semibold whitespace-nowrap transition-colors';

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      {/* min-w-0 on the grid children: DialogContent is a grid, so a nowrap URL would
          otherwise force the column wider than max-w-sm and push the buttons off-screen */}
      <DialogContent className="bg-[#0d1117] border border-[#1e2d40] rounded-2xl w-[calc(100vw-2rem)] max-w-sm p-0 gap-0 overflow-hidden">
        <div className="min-w-0 px-5 py-4 border-b border-[#1e2d40]">
          <div className="flex items-center gap-2 min-w-0">
            <QrCode className="w-4 h-4 text-[#3b82f6] flex-shrink-0" />
            <p className="text-[#f0f4f8] font-bold text-sm truncate">Share {name}</p>
          </div>
          {subtitle && <p className="text-[#8da0b3] text-xs mt-0.5 truncate">{subtitle}</p>}
        </div>

        <div className="min-w-0 p-5 space-y-4">
          {qrCodeData ? (
            <div className="flex justify-center">
              <div className="bg-white rounded-2xl p-3 shadow-lg shadow-black/40">
                <img src={qrCodeData} alt={`QR code linking to ${name}`} className="w-44 h-44 block" />
              </div>
            </div>
          ) : (
            <p className="text-[#8da0b3] text-sm text-center py-4">
              No QR code has been generated for {name} yet.
            </p>
          )}

          <p className="text-[#8da0b3] text-xs text-center">
            Scan or share this link to open {name}&apos;s page and vote.
          </p>

          <div className="min-w-0 bg-[#111927] border border-[#1e2d40] rounded-xl px-3 py-2.5">
            <p className="text-[#8da0b3] text-[11px] truncate" title={absoluteUrl}>{absoluteUrl}</p>
          </div>

          <div className="flex gap-2 min-w-0">
            <button
              type="button"
              onClick={handleShare}
              className={`${actionClass} bg-[#3b82f6] border-[#3b82f6] text-white hover:bg-[#2563eb]`}
            >
              <Share2 className="w-3.5 h-3.5 flex-shrink-0" />
              Share
            </button>
            <button
              type="button"
              onClick={handleCopy}
              className={`${actionClass} bg-[#111927] border-[#1e2d40] text-[#8da0b3] hover:text-[#f0f4f8] hover:border-[#3b82f6]`}
            >
              {copied ? <Check className="w-3.5 h-3.5 flex-shrink-0 text-emerald-400" /> : <LinkIcon className="w-3.5 h-3.5 flex-shrink-0" />}
              {copied ? 'Copied' : 'Copy'}
            </button>
          </div>

          <div className="flex gap-2 min-w-0">
            {qrCodeData && (
              <button
                type="button"
                onClick={handleDownload}
                className={`${actionClass} bg-[#111927] border-[#1e2d40] text-[#8da0b3] hover:text-[#f0f4f8] hover:border-[#3b82f6]`}
              >
                <Download className="w-3.5 h-3.5 flex-shrink-0" />
                Save QR
              </button>
            )}
            <a
              href={url}
              target="_blank"
              rel="noopener noreferrer"
              className={`${actionClass} bg-[#111927] border-[#1e2d40] text-[#8da0b3] hover:text-[#f0f4f8] hover:border-[#3b82f6]`}
            >
              <ExternalLink className="w-3.5 h-3.5 flex-shrink-0" />
              Open page
            </a>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
};

export default ShareQrDialog;
